# Generated by Django 4.0.4 on 2022-05-11 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InputConfKeyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(max_length=32)),
                ('value', models.TextField(max_length=32)),
                ('description', models.TextField(blank=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='PropConfKeyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(max_length=32)),
                ('value', models.TextField(max_length=32)),
                ('description', models.TextField(blank=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=32)),
                ('domain', models.TextField(blank=True, max_length=32)),
                ('description', models.TextField(blank=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='SplunkInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=256)),
                ('index', models.CharField(max_length=32)),
                ('source_type', models.CharField(max_length=64, verbose_name='sourcetype')),
                ('meta', models.CharField(max_length=16, verbose_name='_meta')),
                ('crc_salt', models.CharField(max_length=16, verbose_name='crcSalt')),
                ('tcp_routing', models.CharField(max_length=16, verbose_name='_TCP_ROUTING')),
                ('kvs', models.ManyToManyField(related_name='input_kvs', to='app.inputconfkeyvalue')),
            ],
        ),
        migrations.CreateModel(
            name='SplunkProps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=256)),
                ('kvs', models.ManyToManyField(related_name='props_kvs', to='app.propconfkeyvalue')),
            ],
        ),
        migrations.CreateModel(
            name='Whitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=32)),
                ('description', models.TextField(blank=True, max_length=32)),
                ('servers', models.ManyToManyField(related_name='servers', to='app.server')),
            ],
        ),
        migrations.CreateModel(
            name='SplunkPropsFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, max_length=512)),
                ('props', models.ManyToManyField(related_name='file_props', to='app.splunkprops')),
            ],
        ),
        migrations.CreateModel(
            name='SplunkInputsFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, max_length=512)),
                ('inputs', models.ManyToManyField(related_name='file_inputs', to='app.splunkinput')),
            ],
        ),
        migrations.CreateModel(
            name='SplunkApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wf_id', models.CharField(max_length=16)),
                ('subject', models.CharField(max_length=64)),
                ('cluster', models.CharField(choices=[('shared', 'shared'), ('bus1', 'bus1'), ('bus2', 'bus2'), ('es', 'es'), ('itsi', 'itsi'), ('mltk', 'mltk')], max_length=8)),
                ('repo', models.TextField(max_length=128)),
                ('default_index', models.CharField(max_length=32)),
                ('inputs', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_input_file', to='app.splunkinputsfile')),
                ('members_r', models.ManyToManyField(related_name='members_r', to=settings.AUTH_USER_MODEL)),
                ('members_w', models.ManyToManyField(related_name='members_w', to=settings.AUTH_USER_MODEL)),
                ('moderators', models.ManyToManyField(related_name='moderators', to=settings.AUTH_USER_MODEL)),
                ('props', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_props_file', to='app.splunkpropsfile')),
                ('whitelist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whitelist', to='app.whitelist')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_email', models.TextField(blank=True, max_length=256)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(blank=True, max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('viewed', models.DateTimeField()),
                ('text', models.TextField(max_length=500)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
