# Generated by Django 4.0.4 on 2022-05-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('app_name', models.CharField(blank=True, max_length=128)),
                ('whitelist_file', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='SplunkFileSha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(max_length=128)),
                ('repo_name', models.CharField(max_length=128)),
                ('path_name', models.CharField(max_length=256)),
                ('branch', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='splunkapp',
            name='inputs',
        ),
        migrations.RemoveField(
            model_name='splunkapp',
            name='members_r',
        ),
        migrations.RemoveField(
            model_name='splunkapp',
            name='members_w',
        ),
        migrations.RemoveField(
            model_name='splunkapp',
            name='moderators',
        ),
        migrations.RemoveField(
            model_name='splunkapp',
            name='props',
        ),
        migrations.RemoveField(
            model_name='splunkapp',
            name='whitelist',
        ),
        migrations.RemoveField(
            model_name='splunkinput',
            name='kvs',
        ),
        migrations.RemoveField(
            model_name='splunkinputsfile',
            name='inputs',
        ),
        migrations.RemoveField(
            model_name='splunkprops',
            name='kvs',
        ),
        migrations.RemoveField(
            model_name='splunkpropsfile',
            name='props',
        ),
        migrations.RemoveField(
            model_name='whitelist',
            name='servers',
        ),
        migrations.DeleteModel(
            name='InputConfKeyValue',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='PropConfKeyValue',
        ),
        migrations.DeleteModel(
            name='Server',
        ),
        migrations.DeleteModel(
            name='SplunkApp',
        ),
        migrations.DeleteModel(
            name='SplunkInput',
        ),
        migrations.DeleteModel(
            name='SplunkInputsFile',
        ),
        migrations.DeleteModel(
            name='SplunkProps',
        ),
        migrations.DeleteModel(
            name='SplunkPropsFile',
        ),
        migrations.DeleteModel(
            name='Whitelist',
        ),
    ]
