# Generated by Django 4.0.4 on 2022-05-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_serverclass_splunkfilesha_remove_message_receiver_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='splunkfilesha',
            constraint=models.UniqueConstraint(fields=('repo_name', 'path_name', 'branch'), name='unique_sha_combination'),
        ),
    ]
