# Generated by Django 4.0.4 on 2022-05-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_splunkserverclass_whitelist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SplunkInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=128)),
                ('var', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='splunkapp',
            name='inputs',
            field=models.ManyToManyField(related_name='inputs', to='app.splunkinput'),
        ),
    ]
